name: docker-compose-actions-workflow
on: 

    push:
        branches:
        - 'main'
        
    workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Step 1 - Run Docker 1
        run: docker-compose up
        
      # - name: Step 2 - Run Docker 2
      #   run: docker-compose -f docker-compose.yml -f docker-compose.qa.yml up -d
        
      - name: Step 2 - Attach Report
        uses: actions/upload-artifact@v2
        with:
          name: Report
          path: src/report/report.html

